# Generated by Django 4.1.7 on 2023-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midmorningDjangoRegistrationOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_email', models.CharField(max_length=30)),
                ('s_location', models.CharField(max_length=30)),
                ('s_product', models.CharField(max_length=30)),
            ],
        ),
    ]
